name: first workflow
on: workflow_dispatch
jobs: 
   first-job:
           runs-on: macos-latest
           steps:
               - name: print greeting
                 run: echo "Hello mohammed"
               - name: print goodbye
                 run: echo "Done - bye mohammed!"
           
